# Generated by Django 4.2.6 on 2023-11-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_published_books_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='published_books', to='books.author'),
        ),
    ]
